export const REWARD_CARDS: Record<'romantic' | 'flirty' | 'spicy', string[]> = {
  romantic: [
    "Tell your partner one thing they do that makes you feel completely safe.",
    "Name a moment this week when you felt most grateful for them.",
    "Share a memory from your early days together that still makes you smile.",
    "Describe what you admire most about your partner's character.",
    "What's one small thing your partner does that shows they care?",
    "Share a hope or dream you have for your future together.",
    "What's your favorite way to reconnect after a long day?",
    "Tell your partner something you've learned from them.",
    "What quality of your partner's makes you feel most loved?",
    "Share a moment when you felt especially proud of your partner.",
  ],
  flirty: [
    "Give your partner the best kiss you've got. No holding back.",
    "Whisper one thing you've been meaning to say all day.",
    "Share what you find most attractive about your partner right now.",
    "Describe your favorite memory of being physically close.",
    "What's one thing you'd love to do together tonight?",
    "Tell your partner what you're looking forward to most later.",
    "Share a playful secret fantasy about your partner.",
    "What's the sexiest thing about your partner's personality?",
    "Describe the perfect romantic evening together.",
    "What makes you feel most desired by your partner?",
  ],
  spicy: [
    // Using flirty rewards as fallback for v1.1
    "Give your partner the best kiss you've got. No holding back.",
    "Whisper one thing you've been meaning to say all day.",
    "Share what you find most attractive about your partner right now.",
    "Describe your favorite memory of being physically close.",
    "What's one thing you'd love to do together tonight?",
    "Tell your partner what you're looking forward to most later.",
    "Share a playful secret fantasy about your partner.",
    "What's the sexiest thing about your partner's personality?",
    "Describe the perfect romantic evening together.",
    "What makes you feel most desired by your partner?",
  ],
};